### ISSUE TITLE
[Demo UI] When 'splash screen' should not remove pre-existing sections

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-ui#31]
A short time after the splash screen appears it disappears again.

However, this is currently achieved by deleting all sections, including any sections that had been created before the splash screen was opened. It would be better if the only the newly created splash-screen section was deleted.

**Comment by senakafdo** [comment]
@jamesscottbrown, as also discussed previously I don't see an issue in the splash screen deleting content of the section in which it is intended to be displayed in. Anyone who loaded anything onto that space can reload the content afterwards. However, the splash screen must not delete sections created in other spaces as also noted in #32. I agreed with that point of yours.

**Comment by jamesscottbrown** [comment]
I think of the splash screen as essentially a modal window that is opened on top of existing content, and then closed. In traditional window managers, opening a window and then closing it does not close prexisting windows. 

(In my view, the blank screen and logo displayed by the GDO Loader *should* alos act as overlays rather than replacements, but they do not because they were implemented before OVE was written, when there was no support for superimposing sections/content.)


> Anyone who loaded anything onto that space can reload the content afterwards.

This is not necessarily true. A user might not have any record of the state of OVE before all sections were deleted, so may not be able to easily restore it (e.g., they may have to search for the URLs of assets they had opened, and re-position sections). It is also not guaranteed that the assets can simply be reloaded (for example, they might have been served from the laptop of someone who has left the building).

I think that applications should generally be very careful about deleting sections that they have not themselves created, and should do so only when necessary or explicitly requested by the user.
