### ISSUE TITLE
[Launcher UI] Update docs for new launcher

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-ui#76]

**Comment by jamesscottbrown** [comment]
This is mostly addressed by https://github.com/ove/ove-ui/pull/77.

However, I can't just add a screenshot of the new launcher because of https://github.com/ove/ove-docs/issues/38

**Comment by senakafdo** [comment]
You can add screenshots, @jamesscottbrown. See https://ove.readthedocs.io/en/stable/docs/USAGE.html.

The issue you point out is due to some other reason and only impacts files on LFS, I think it may be some issue on GitHub itself. Will have to investigate further.

**Comment by jamesscottbrown** [comment]
I've also also updated the OVE Usage page (and added a screenshot) in https://github.com/ove/ove-docs/pull/39
